import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#32302c',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#f7fff2',
        'surface-container-high': '#ece7e1',
        'on-surface-variant': '#524439',
        'inverse-on-surface': '#f5f0e9',
        'surface-container-low': '#f8f3ec',
        'inverse-primary': '#ffb77c',
        'primary-fixed': '#ffdcc2',
        'secondary-fixed-dim': '#eabcb8',
        'success-leaf': '#5f7c5f',
        'on-background': '#1d1c18',
        'outline': '#857467',
        'background': '#fef9f2',
        'surface-container': '#f2ede6',
        'secondary-container': '#ffcfcb',
        'outline-variant': '#d8c3b4',
        'on-secondary': '#ffffff',
        'tertiary': '#476347',
        'surface-dim': '#ded9d3',
        'on-primary-fixed-variant': '#6d3900',
        'error': '#ba1a1a',
        'primary-container': '#a66528',
        'tertiary-fixed-dim': '#afcfad',
        'error-container': '#ffdad6',
        'primary': '#894d10',
        'on-error': '#ffffff',
        'on-surface': '#1d1c18',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e6e2db',
        'primary-fixed-dim': '#ffb77c',
        'on-primary-fixed': '#2e1500',
        'secondary': '#795553',
        'surface-bright': '#fef9f2',
        'surface-tint': '#8c4f13',
        'on-primary': '#ffffff',
        'tertiary-container': '#5f7c5f',
        'on-primary-container': '#fffbff',
        'surface': '#fef9f2',
        'on-secondary-container': '#7a5654',
        'tertiary-fixed': '#cbebc8',
        'on-tertiary-fixed': '#06210b',
        'surface-container-highest': '#e6e2db',
        'secondary-fixed': '#ffdad7',
        'on-secondary-fixed': '#2e1413',
        'on-tertiary-fixed-variant': '#324d33',
        'on-secondary-fixed-variant': '#5f3e3c',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'section-sm': '40px',
        'section-lg': '120px',
        'section-md': '80px',
        'base': '8px',
        'gutter': '24px',
        'container-max': '1280px',
        'section-padding': '80px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'h1': ['Newsreader', 'serif'],
        'h2': ['Newsreader', 'serif'],
        'h3': ['Newsreader', 'serif'],
        'h1-mobile': ['Newsreader', 'serif'],
        'body-md': ['"Work Sans"', 'sans-serif'],
        'body-lg': ['"Work Sans"', 'sans-serif'],
        'label-sm': ['"Work Sans"', 'sans-serif'],
      },
      fontSize: {
        'h1': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h2': ['36px', { lineHeight: '1.2', fontWeight: '500' }],
        'h3': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'h1-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
